package edu.tuichu.heuristic;

public enum FactorType {
	WHITEWIN,
	BLACKWIN,
	KING_IN_CASTLE,
	WHITE_PAWNS,
	BLACK_PAWNS,
	EATEN_WHITE_PAWNS,
	EATEN_BLACK_PAWNS,
	DISTANCE_TO_WIN,
	WHITE_PAWNS_IN_WIN_CELLS,
	BLACK_PAWNS_IN_WIN_CELLS,
	WHITE_PAWNS_ADJACENT_TO_KING,
	BLACK_PAWNS_ADJACENT_TO_KING,
	WHITE_PAWNS_IN_KINGS_ROW,
	BLACK_PAWNS_IN_KINGS_ROW,
	WHITE_PAWNS_IN_KINGS_COLUMN,
	BLACK_PAWNS_IN_KINGS_COLUMN,
	WHITE_AROUND_KING,
	BLACK_AROUND_KING
}