package edu.tuichu.heuristic;

public enum FactorType {
	WHITEWIN,
	BLACKWIN,
	KING_IN_CASTLE,
	EATEN_WHITE_PAWNS,
	EATEN_BLACK_PAWNS,
	DISTANCE_TO_WIN,
	WHITE_PAWNS_ADJACENT_TO_KING,
	BLACK_PAWNS_ADJACENT_TO_KING,
	WHITE_AROUND_KING,
	BLACK_AROUND_KING
}